services:
  postgres:
    image: postgres:16.3
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata

    volumes:
      - ./output/.pg/data:/var/lib/postgresql/data/pgdata

  pgmg:
    build:
      dockerfile_inline: |
        FROM node:20-alpine as base
        RUN apk add inotify-tools

        CMD npx nodemon -L --watch "./migrations/*.js" --watch "./tests/*.js" --exec npm start

    working_dir: $PWD/services/pgmg
    user: 1000:1000
    volumes:
      - ./services/pgmg:$PWD/services/pgmg
      - .:$PWD/services/pgmg/node_modules/pgmg