services:
  postgres:
    build: 
      dockerfile_inline: |
        FROM postgres:16.3

        USER root

        RUN apt-get update -y && apt-get install nano -y

        USER postgres
    ports:
      - 5435:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/pg_data
      EDITOR: nano
    user: root
    volumes:
      - ./output/.pg/data:/var/lib/pg_data
      # for caching psql history
      - ./output/.pg/home:/home/postgres/
      # for scratch queries, mkdir before mounting
      - ./output/.pg/queries:/home/postgres/queries

  pgmg:
    build:
      dockerfile_inline: |
        FROM node:20-alpine as base
        RUN apk add inotify-tools

        CMD npx nodemon -L --watch "./migrations/*.js" --watch "./tests/*.js" --exec npm start

    working_dir: $PWD/services/pgmg
    user: 1000:1000
    environment:
      API_DB_URL: postgres://api:password@postgres:5432/postgres

      ENC_KEY_JWK: '{"key_ops":["encrypt","decrypt"],"ext":true,"kty":"oct","k":"55kA5KZFUJuoNHaWGk6BtZY7_RXthyhXpMltBLtl2ZQ","alg":"A256CBC"}'
    volumes:
      - ./services/pgmg:$PWD/services/pgmg
      - .:$PWD/services/pgmg/node_modules/pgmg
    depends_on:
      - postgres